STRWEB/LR2/pizzeria/blog/urls.py
# blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about_company, name='about_company'),
    path('news/', views.news_list, name='news_list'),
    path('post/<int:post_id>/', views.post_view, name='news_post'),
    path('faq/', views.faq_list, name='faq_list'),
    path('promo/', views.promo_list, name='promo_list'),
    path('reviews/', views.review_list, name='reviews'),
    path('submit_review/', views.submit_review, name='submit_review'),
    path('vacancy/', views.vacancy_view, name='vacancy'),
    path('employee/', views.employee_view, name='employee'),
    path('test/', views.test, name='test'),
]

STRWEB/LR2/pizzeria/pizza/urls.py
from django.urls import path

from . import views
from .views import order_list

app_name = 'pizza'

urlpatterns = [
    path('', views.index, name='homepage'),
    path('pizza_list/', views.pizza_list, name='pizza_list'),
    path('pizza/<int:pizza_id>/', views.pizza_detail, name='pizza_detail'),
    path('pizza/edit/<int:pizza_id>/', views.pizza_edit, name='pizza_edit'),
    path('order/<int:pizza_id>/', views.add_to_cart, name='order_pizza'),
    path('confirm_order/', views.confirm_order, name='confirm_order'),
    path('cart/', views.view_cart, name='view_cart'),
    path('payment/', views.payment_view, name='payment'),
    path('remove_from_cart/<int:pizza_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('orders/', order_list, name='order_list'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('orders/<int:order_id>/finish/', views.finish_order, name='finish_order'),
]

STRWEB/LR2/pizzeria/pizzeria/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('pizza.urls')),
                  path('user/', include('registration.urls')),
                  path('blog/', include('blog.urls'))
                  # path('media', )
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

STRWEB/LR2/pizzeria/registration/urls.py
from django.urls import path

from . import views

app_name = 'registration'

urlpatterns = [
    path('create_account/', views.create_account, name='create_account'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='user_profile'),
]

STRWEB/LR2/pizzeria/pizza/models.py
from django.contrib.auth.models import User
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=100)
    sauce = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    #category = models.CharField(max_length=100)
    image = models.ImageField(upload_to='media/pizza/')

    def __str__(self):
        return self.name


class Order(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE, related_name='client_orders')
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    total_price = models.DecimalField(max_digits=8, decimal_places=2)
    courier = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='courier_orders', null=True,
                                blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=False, null=True, blank=True)
    status = models.BooleanField(default=False)
    discount = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    def __str__(self):
        return f"Order {self.id} by {self.client.username}"

    def save(self, *args, **kwargs):
        self.total_price = float(self.quantity) * float(self.pizza.price) * (1 - float(self.discount))
        super().save(*args, **kwargs)


class PromoCode(models.Model):
    code = models.CharField(max_length=50, unique=True)
    discount = models.DecimalField(max_digits=5, decimal_places=2)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.code

STRWEB/LR2/pizzeria/pizza/forms.py
# pizza/forms.py

from django import forms
from django.contrib.auth.models import User

from .models import Pizza, Order, PromoCode


class PizzaFilterForm(forms.Form):
    SORT_CHOICES = [
        ('price_asc', 'Цена по возрастанию'),
        ('price_desc', 'Цена по убыванию'),
    ]
    sort_by = forms.ChoiceField(choices=SORT_CHOICES, required=False)
    sauce_search = forms.CharField(max_length=100, required=False, label='Поиск по соусу', initial="")


class PizzaForm(forms.ModelForm):
    price = forms.CharField(widget=forms.TextInput(attrs={'type': 'number'}))

    class Meta:
        model = Pizza
        fields = ['name', 'sauce', 'price']


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['pizza', 'quantity', 'courier']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['courier'].required = False


class PromoCodeForm(forms.ModelForm):
    class Meta:
        model = PromoCode
        fields = ['code', 'discount', 'is_active']


class OrderUpdateForm(forms.ModelForm):
    courier = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=True), required=False)

    class Meta:
        model = Order
        fields = ['status', 'courier']

STRWEB/LR2/pizzeria/pizza/views.py
# pizza/views.py
from datetime import datetime
from venv import logger

from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render

from .forms import PizzaForm, OrderForm, PizzaFilterForm
from .models import Pizza, Order, PromoCode
from registration.models import Courier


def index(request):
    logger.info("Redirecting to pizza list")
    return redirect('pizza:pizza_list')


def pizza_list(request):
    logger.debug("Fetching all pizzas and promo codes")
    pizzas = Pizza.objects.all()
    promo_codes = PromoCode.objects.all()

    form = PizzaFilterForm(request.GET)
    if form.is_valid():
        logger.debug("Pizza filter form is valid")
        if form.cleaned_data['sauce_search']:
            logger.debug(f"Filtering pizzas with sauce containing: {form.cleaned_data['sauce_search']}")
            pizzas = pizzas.filter(sauce__icontains=form.cleaned_data['sauce_search'])
        if form.cleaned_data['sort_by'] == 'price_asc':
            logger.debug("Sorting pizzas by ascending price")
            pizzas = pizzas.order_by('price')
        elif form.cleaned_data['sort_by'] == 'price_desc':

            logger.debug("Sorting pizzas by descending price")
            pizzas = pizzas.order_by('-price')

    context = {
        'pizzas': pizzas,
        'promo_codes': promo_codes,
        'form': form,
    }
    logger.info("Rendering pizza list")
    return render(request, 'pizza_list.html', context)


@login_required
def pizza_detail(request, pizza_id):
    logger.debug(f"Fetching pizza with id: {pizza_id}")
    pizza = get_object_or_404(Pizza, id=pizza_id)
    logger.info("Rendering pizza detail")
    return render(request, 'pizza_detail.html', {'pizza': pizza})


@login_required
def pizza_create(request):
    if request.method == 'POST':
        logger.debug("Creating new pizza")
        form = PizzaForm(request.POST)
        if form.is_valid():
            form.save()
            logger.info("New pizza created successfully")
            return redirect('pizza:pizza_list')
    else:
        form = PizzaForm()
    return render(request, 'pizza_form.html', {'form': form})


def add_to_cart(request, pizza_id):
    logger.debug(f"Adding pizza with id {pizza_id} to the cart")
    pizza = get_object_or_404(Pizza, id=pizza_id)

    if 'cart' not in request.session:
        request.session['cart'] = {}

    cart = request.session['cart']

    if str(pizza_id) in cart:
        cart[str(pizza_id)] += 1
    else:
        cart[str(pizza_id)] = 1

    request.session['cart'] = cart
    logger.info("Pizza added to the cart successfully")

    return redirect('pizza:view_cart')


@login_required
def view_cart(request):
    if 'cart' not in request.session:
        request.session['cart'] = {}

    logger.debug("Viewing shopping cart")
    cart = request.session.get('cart', {})
    pizzas_in_cart = Pizza.objects.filter(id__in=cart.keys())

    total_price = sum(cart[str(pizza.id)] * pizza.price for pizza in pizzas_in_cart)

    return render(request, 'view_cart.html',
                  {'cart': cart, 'pizzas_in_cart': pizzas_in_cart, 'total_price': total_price})


@login_required
def remove_from_cart(request, pizza_id):
    if 'cart' not in request.session:
        request.session['cart'] = {}

    logger.debug(f"Removing pizza with id {pizza_id} from the cart")

    if 'cart' in request.session:
        cart = request.session['cart']

        if str(pizza_id) in cart:
            if cart[str(pizza_id)] > 1:
                cart[str(pizza_id)] -= 1
            else:
                del cart[str(pizza_id)]

        request.session['cart'] = cart
        logger.info("Pizza removed from the cart successfully")

    return redirect('pizza:view_cart')


@login_required
def clear_cart(request):
    if 'cart' not in request.session:
        request.session['cart'] = {}

    logger.debug("Clearing the shopping cart")

    if 'cart' in request.session:
        del request.session['cart']

    logger.info("Cart cleared successfully")

    return redirect('pizza:view_cart')


@login_required
def order_pizza(request, pizza_id):
    logger.debug(f"Ordering pizza with id: {pizza_id}")
    pizza = get_object_or_404(Pizza, id=pizza_id)
    quantity = 1  # Assume a default quantity for simplicity, you might want to modify this
    total_price = quantity * pizza.price
    order = Order.objects.create(client=request.user, pizza=pizza, quantity=quantity, total_price=total_price)
    logger.info("Pizza ordered successfully")
    return render(request, 'order_confirmation.html', {'order': order, 'pizza': pizza})


@login_required
def confirm_order(request):
    logger.debug("Confirming order")

    if 'cart' not in request.session:
        request.session['cart'] = {}

    cart = request.session['cart']

    promo_code = request.POST.get('promo_code')
    orders = []
    for pizza_id in cart.keys():
        pizza = get_object_or_404(Pizza, id=pizza_id)
        order = Order.objects.create(client=request.user, pizza=pizza, quantity=cart[str(pizza_id)],
                                     total_price=pizza.price * cart[str(pizza_id)])
        order.save()
        orders.append(order)
    cart = {}
    request.session['cart'] = cart
    if promo_code:
        try:
            promo = get_object_or_404(PromoCode, code=promo_code, is_active=True)
            for order in orders:
                order.discount = promo.discount
                order.save()
        except PromoCode.DoesNotExist:
            error_message = "Invalid or inactive promo code"
            return render(request, 'order_confirmation.html', {'order': order, 'error_message': error_message})
    return redirect(to='pizza:payment')

@login_required
def payment_view(request):
    return render(request, 'payment.html')

@login_required
def pizza_edit(request, pizza_id):
    logger.debug(f"Editing pizza with id: {pizza_id}")
    pizza = get_object_or_404(Pizza, id=pizza_id)
    if request.method == 'POST':
        form = PizzaForm(request.POST, instance=pizza)
        if form.is_valid():
            form.save()
            logger.info(f"Pizza with id {pizza_id} updated successfully")
            return redirect('pizza:pizza_detail', pizza_id=pizza.id)
        else:
            logger.warning("Pizza form is invalid")
    else:
        form = PizzaForm(instance=pizza)
    return render(request, 'pizza_form.html', {'form': form})


@login_required
def order_create(request):
    if request.method == 'POST':
        logger.debug("Creating new order")
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.client = request.user
            order.total_price = order.pizza.price * order.quantity
            order.save()
            logger.info("New order created successfully")
            return redirect('pizza:order_list')
        else:
            logger.warning("Order form is invalid")
    else:
        form = OrderForm()
    return render(request, 'order_form.html', {'form': form})


def staff_required(user):
    return user.is_staff


@user_passes_test(staff_required)
def order_list(request):
    orders = Order.objects.all().order_by('-created_at')
    logger.info("Rendering pizza detail")
    return render(request, 'order_list.html', {'orders': orders})


@user_passes_test(staff_required)
def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order_detail.html', {'order': order})


@user_passes_test(staff_required)
def finish_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.status = True
    order.updated_at = datetime.now()
    order.courier = request.user
    courier = get_object_or_404(Courier, user=order.courier)
    courier.total_deliveries += 1
    courier.save()
    order.save()
    return redirect('pizza:order_list')

STRWEB/LR2/pizzeria/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PizzeriaNapoli</title>
    <link rel="icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    {% include 'meta.html' %}
    {% block head %}{% endblock %}
</head>
<body>
<div class="wrapper">
    <header>
        {% block top_navbar %}
            <nav class="navbar">
                <a class="navbar-brand" href="{% url 'pizza:pizza_list' %}">PizzeriaNapoli</a>
                <a href="{% url 'blog:home' %}">Домашняя</a>
                <a href="{% url 'blog:reviews' %}">Отзывы</a>
                <div class="dropdown ">
                    <select onchange="if (this.value) window.location.href=this.value">
                        <option value="">О компании</option>
                        <option value="{% url 'blog:about_company' %}">О компании</option>
                        <option value="{% url 'blog:news_list' %}">Новости</option>
                        <option value="{% url 'blog:faq_list' %}">ЧАВО</option>
                        <option value="{% url 'blog:promo_list' %}">Промокоды</option>
                        <option value="{% url 'blog:vacancy' %}">Вакансии</option>
                        <option value="{% url 'blog:employee' %}">Сотрудники</option>
                    </select>
                </div>

                {% if request.user.is_staff %}
                    <a href="{% url 'pizza:order_list' %}">Заказы</a>
                {% endif %}

                <div class="push">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'registration:user_profile' %}">Welcome {{ request.user }}</a>
                        <a href="{% url 'pizza:view_cart' %}">Корзина</a>
                    {% else %}
                        <a href="{% url 'registration:login' %}">Login/register</a>
                    {% endif %}
                </div>
                {% block navbar %}
                {% endblock navbar %}
            </nav>

        {% endblock top_navbar %}
    </header>

    <main >
        {% block content %}{% endblock %}
    </main>

    <footer class="footer">
        <div>
            <p><b>&copy; 2024 PizzeriaNapoli</b></p>
        </div>
    </footer>
</div>

</body>
</html>

STRWEB/LR2/pizzeria/templates/create_account.html
{% extends "form_base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}
{% block content %}

    <div>
        <h2>Регистрация</h2>
    </div>
    <div>
        <form method="post" novalidate>
            <div>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Зарегистрироваться</button>
            </div>
        </form>
    </div>

{% endblock %}

STRWEB/LR2/pizzeria/templates/form_base.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <div>
            {% block form %}
            {% endblock form %}
        </div>
    </div>
{% endblock content %}

STRWEB/LR2/pizzeria/templates/login.html
{% extends 'form_base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}

{% block form %}
    <div class="container">
        <h1>Login</h1>
        <h5>
            <a href="{% url 'registration:create_account' %}">
                or create an account
            </a>
        </h5>

        <form method="POST">
            <div>
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Login">
            </div>
        </form>
    </div>
{% endblock form %}

STRWEB/LR2/pizzeria/templates/meta.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no">


<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="description"
      content="Delicious pizzas, pastas, and more at PizzeriaNapoli. Order online for delivery or pickup!">
<meta name="keywords" content="pizza, pasta, Italian cuisine, delivery, pickup, PizzeriaNapoli">

<meta property="og:title" content="PizzeriaNapoli - Best Pizza in Town">
<meta property="og:description"
      content="Delicious pizzas, pastas, and more at PizzeriaNapoli. Order online for delivery or pickup!">
<meta property="og:image" content="{% static 'meta_image.png' %}">
<meta property="og:url" content="https://pizzerianapoli.com">
<meta property="og:type" content="website">
<meta property="twitter:card" content="summary_large_image">
<meta name="twitter:domain" content="pizzerianapoli.com">
<meta name="twitter:url" content="https://pizzerianapoli.com">
<meta name="twitter:title" content="PizzeriaNapoli - Best Pizza in Town">
<meta name="twitter:description"
      content="Delicious pizzas, pastas, and more at PizzeriaNapoli. Order online for delivery or pickup!">
<meta name="twitter:image" content="{% static 'meta_image.png' %}">

<link rel="stylesheet" href="{% static 'css/variables.css' %}">
<link rel="stylesheet" href="{% static 'css/layout.css' %}">
<link rel="stylesheet" href="{% static 'css/components.css' %}">
<link rel="stylesheet" href="{% static 'css/media.css' %}">
<link rel="stylesheet" href="{% static 'css/hh.css' %}">

STRWEB/LR2/pizzeria/templates/order_confirmation.html
{% extends "base.html" %}

{% block content %}
    <div>
        <h1>Заказ подтвержден <img src="{% static 'pizza-svgrepo-com.svg' %}"></h1>

        <p>Вы успешно заказали пиццу: {{ order.pizza.name }}.</p>
        <p>Количество: {{ order.quantity }}</p>
        <p>Общая цена: ${{ order.total_price }}</p>
        <form method="post" action="{% url 'pizza:confirm_order' order_id=order.id %}">
            {% csrf_token %}
            <div >
                <label for="promo_code">Промокод:</label>
                <input type="text"  id="promo_code" name="promo_code">
            </div>
            {% if error_message %}
            <div  role="alert">
                {{ error_message }}
            </div>
            {% endif %}
            <button type="submit">Подтвердить</button>
        </form>
        <a href="{% url 'pizza:pizza_list' %}" >Вернуться к списку пицц</a>
    </div>
{% endblock %}

STRWEB/LR2/pizzeria/templates/order_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Order Detail</h1>
    <p>ID: {{ order.id }}</p>
    <p>Client: {{ order.client.username }}</p>
    <p>Pizza: {{ order.pizza.name }}</p>
    <p>Quantity: {{ order.quantity }}</p>
    <p>Total Price: {{ order.total_price }}</p>
    <p>Created At: {{ order.created_at }}</p>
    <p>Status: {{ order.status }}</p>
    {% if not order.status %}
        <a href="{% url 'pizza:finish_order' order.id %}">Finish Order</a>
    {% endif %}
    <a href="{% url 'pizza:order_list' %}">Back to Orders</a>
{% endblock %}

STRWEB/LR2/pizzeria/templates/order_form.html
{% extends "base.html" %}

{% block content %}
    <div>
        <div>
            <div>
                <div>
                    <h5 align="center">Создать Заказ</h5>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

STRWEB/LR2/pizzeria/templates/order_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Order List <img src="{% static 'pizza-svgrepo-com.svg' %}"></h1>
    <table>
        <thead>
        <tr>
            <th>ID</th>
            <th>Client</th>
            <th>Pizza</th>
            <th>Quantity</th>
            <th>Total Price</th>
            <th>Created At</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.client.username }}</td>
                <td>{{ order.pizza.name }}</td>
                <td>{{ order.quantity }}</td>
                <td>{{ order.total_price }}</td>
                <td>{{ order.created_at }}</td>
                <td>{{ order.status }}</td>
                <td>
                    <a href="{% url 'pizza:order_detail' order.id %}">View</a>
                    {% if not order.status %}
                        <a href="{% url 'pizza:finish_order' order.id %}">Finish Order</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

STRWEB/LR2/pizzeria/templates/payment.html
{% extends "base.html" %}

{% block content %}
    <h1>Подтвердить оплату</h1>

    <a href="{% url 'pizza:pizza_list' %}">подтвердить</a>
{% endblock %}

STRWEB/LR2/pizzeria/templates/pizza_detail.html
{% extends "base.html" %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/pizzaabout.css' %}">
{% endblock %}


{% block content %}

<div class="pizza-container">
    <h2 class="pizza-name">{{ pizza.name }}</h2>
    <p class="pizza-price"><strong>Цена:</strong> ${{ pizza.price }}</p>
    {% if pizza.sauce %}
        <p class="pizza-sauce"><strong>Соус:</strong> {{ pizza.sauce }}</p>
    {% endif %}
    {% if pizza.image %}
        <img src="{{ pizza.image.url }}" alt="{{ pizza.name }}" class="pizza-image">
    {% endif %}
    {% if request.user.is_staff %}
        <div class="edit-link">
            <a href="{% url 'pizza:pizza_edit' pizza.id %}">Редактировать</a>
        </div>
    {% endif %}
    <div class="order-link">
        <a href="{% url 'pizza:order_pizza' pizza.id %}">Заказать</a>
    </div>
</div>

{% endblock %}

STRWEB/LR2/pizzeria/templates/pizza_form.html
{% extends "base.html" %}

{% block content %}
    <div>
        <div>
            <div>
                <div>
                    <h5 align="center">Создать/Редактировать Пиццу</h5>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

STRWEB/LR2/pizzeria/templates/pizza_list.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/pizzalist.css' %}">
{% endblock %}

{% block content %}
    <div class="pizza-list" itemscope itemtype="https://schema.org/ItemList">
        <h1 class="pizza-title">Наши Пиццы <img src="{% static 'pizza-svgrepo-com.svg' %}" alt="Pizza Icon"></h1>

        <form class="filter-form" method="get">
            <div class="form-group">
                <div class="form-select">
                    <select name="sort_by" class="sort-select">
                        {% for value, label in form.fields.sort_by.choices %}
                            <option value="{{ value }}"
                                    {% if value == form.sort_by.value %}selected{% endif %}>{{ label }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-input">
                    <input type="text" name="sauce_search" class="sauce-search" placeholder="Поиск по соусу"
                           value="{{ form.sauce_search.value }}">
                </div>
                <div class="form-button">
                    <button type="submit" class="filter-button">Фильтр</button>
                </div>
            </div>
        </form>

        <div class="card-container">
            {% for pizza in pizzas %}
                <div class="card-main" itemscope itemtype="https://schema.org/MenuItem">
                    <h3 class="card-title" itemprop="name">{{ pizza.name }}</h3>

                    {% if pizza.image %}
                        <img itemprop="image" src="{{ pizza.image.url }}" alt="{{ pizza.name }}" class="pizza-image">
                    {% endif %}
                    <div class="card-description">
                        <span itemprop="price" class="pizza-price">{{ pizza.price }}</span>
                        <span><strong>Цена:</strong> $ </span>

                        {% if pizza.sauce %}
                            <p><strong>Соус:</strong> {{ pizza.sauce }}</p>
                        {% endif %}
                    </div>
                    {% if request.user.is_authenticated %}
                        <a class="card-link" href="{% url 'pizza:pizza_detail' pizza.id %}">Подробнее</a>
{#                        <a class="card-link" href="{% url 'pizza:order_pizza' pizza.id %}">Заказать</a>#}
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

STRWEB/LR2/pizzeria/templates/view_cart.html
{% extends "base.html" %}
{% load filters %}
{% load static %}

{% block content %}
    <h1>Shopping Cart <img src="{% static 'pizza-svgrepo-com.svg' %}"></h1>

    <ul>
        {% for pizza in pizzas_in_cart %}
            <li>
                {{ pizza.name }} - Quantity: {{ cart|get_item:pizza.id }} - Price: ${{ pizza.price }}
                <form action="{% url 'pizza:order_pizza' pizza.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Добавить в корзину</button>
                </form>
                <form action="{% url 'pizza:remove_from_cart' pizza.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Удалить из корзины</button>
                </form>
            </li>
        {% endfor %}
    </ul>


    <a href="{% url 'pizza:pizza_list' %}">Back to Pizza List</a>

    {% if pizzas_in_cart|length > 0 %}
        <p>Total Price: ${{ total_price }}</p>

        <form method="post" action="{% url 'pizza:confirm_order' %}">
            {% csrf_token %}
            <div>
                <label for="promo_code">Промокод:</label>
                <input type="text" id="promo_code" name="promo_code">
            </div>
            {% if error_message %}
                <div role="alert">
                    {{ error_message }}
                </div>
            {% endif %}
            <button type="submit">Подтвердить</button>
        </form>
        <form action="{% url 'pizza:confirm_order' %}" method="post">
            {% csrf_token %}
            <button type="submit">Очистить корзину</button>
        </form>
    {% else %}
        <p>Корзина пуста</p>
    {% endif %}
{% endblock %}