STRWEB/LR2/pizzeria/blog/urls.py
# blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about_company, name='about_company'),
    path('news/', views.news_list, name='news_list'),
    path('post/<int:post_id>/', views.post_view, name='news_post'),
    path('faq/', views.faq_list, name='faq_list'),
    path('promo/', views.promo_list, name='promo_list'),
    path('reviews/', views.review_list, name='reviews'),
    path('submit_review/', views.submit_review, name='submit_review'),
    path('vacancy/', views.vacancy_view, name='vacancy'),
    path('employee/', views.employee_view, name='employee'),
    path('test/', views.test, name='test'),
]

STRWEB/LR2/pizzeria/pizzeria/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('pizza.urls')),
                  path('user/', include('registration.urls')),
                  path('blog/', include('blog.urls'))
                  # path('media', )
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

STRWEB/LR2/pizzeria/registration/urls.py
from django.urls import path

from . import views

app_name = 'registration'

urlpatterns = [
    path('create_account/', views.create_account, name='create_account'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='user_profile'),
]

STRWEB/LR2/pizzeria/blog/models.py
from django.db import models


class CompanyInfo(models.Model):
    description = models.TextField()

    def __str__(self):
        return "Company Information"


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='news_images/', blank=True, null=True)
    published_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class FAQ(models.Model):
    question = models.CharField(max_length=200)
    answer = models.TextField()
    added_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question


class Review(models.Model):
    user_name = models.CharField(max_length=200)
    title = models.TextField()
    content = models.TextField()
    added_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user_name


class LogoCompanies(models.Model):
    company_name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='news_images/', blank=True, null=True)

    def __str__(self):
        return self.company_name


class Employee(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='employee_images/', blank=True, null=True)

    def __str__(self):
        return self.name


class Vacancy(models.Model):
    description = models.TextField(null=False, max_length=1000)

    def __str__(self):
        return self.description.split(' ')[0]

STRWEB/LR2/pizzeria/blog/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content']

STRWEB/LR2/pizzeria/blog/views.py
# Create your views here.
import random
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from pizza.models import PromoCode

from .forms import ReviewForm
from .models import Post, CompanyInfo, FAQ, Review, LogoCompanies, Vacancy, Employee


def home(request):
    latest_post = Post.objects.order_by('-published_date').first()
    images = ['pizzeria_promo_1.png', 'pizzeria_promo_2.png', 'pizzeria_promo_3.png']  # List of image paths
    random_image = random.choice(images)  # Select a random image from the list
    logo_companies = LogoCompanies.objects.all()
    return render(request, 'blog/home.html', {'latest_post': latest_post,
                                              'random_image': random_image, 'logo_companies': logo_companies})


def about_company(request):
    return render(request, 'blog/about_company.html')


def post_view(request, post_id):
    post = Post.objects.get(id=post_id)
    return render(request, 'blog/news_post.html', {'post': post})


def news_list(request):
    posts = Post.objects.all().order_by('-published_date')
    return render(request, 'blog/news_list.html', {'posts': posts})


def faq_list(request):
    faqs = FAQ.objects.all().order_by('-added_date')
    return render(request, 'blog/faq_list.html', {'faqs': faqs})


def promo_list(request):
    promos = PromoCode.objects.all().order_by('-is_active')
    for promo in promos:
        promo.discount *= 100
    return render(request, 'blog/promo_list.html', {'promos': promos})


def review_list(request):
    reviews = Review.objects.all().order_by('added_date')
    return render(request, 'blog/reviews.html', {'reviews': reviews})

def test(request):
    return render(request, 'blog/test.html')


def vacancy_view(request):
    vacancies = Vacancy.objects.all()
    return render(request, 'blog/vacancy.html', {'vacancies': vacancies})


def employee_view(request):
    workers = Employee.objects.all()
    return render(request, 'blog/employee.html', {'workers': workers})


@login_required
def submit_review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            # Process the form data
            # Assuming you have a Review model to save the review data
            review = form.save(commit=False)
            review.user_name = request.user.first_name  # Assuming you have a user field in your Review model
            review.added_date = datetime.now()
            review.save()
            return redirect('blog:reviews')  # Redirect to a success page after submitting the review
    else:
        form = ReviewForm()

    return render(request, 'submit_review.html', {'form': form})

STRWEB/LR2/pizzeria/templates/blog/about_company.html
{% extends 'base_blog.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/aboutblog.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="company-info">
            <h1 class="company-title">О компании <img src="{% static 'pizza-svgrepo-com.svg' %}" class="company-icon">
            </h1>
            <p class="company-description">Добро пожаловать в нашу пиццерию! Мы специализируемся на приготовлении
                вкуснейших пицц и итальянских блюд.</p>
        </div>
        <video controls class="company-video">
            <source src="{% static 'video.webm' %}" type="video/webm"/>
        </video>
        <section class="sertificate">

        </section>

        <h2 class="history-title">История пиццерии</h2>
        <p class="history-description">Наша пиццерия была основана в 2005 году двумя братьями-пекарями из Неаполя. С тех
            пор мы радуем наших клиентов ароматными итальянскими блюдами.</p>
        <h2 class="specialization-title">Специализация</h2>
        <p class="specialization-description">Мы гордимся нашими оригинальными рецептами и использованием только свежих
            ингредиентов. Попробуйте нашу пиццу по-неаполитански или пасту аль-денте!</p>
        <h2 class="contact-title">Реквизиты</h2>
        <p class="contact-info">Адрес: ул. Пиццерная, д. 10, г. Милан</p>
        <p class="contact-info">Телефон: +123 456 7890</p>
        <p class="contact-info">Email: info@pizzeria.com</p>
    </div>
{% endblock %}

STRWEB/LR2/pizzeria/templates/blog/base_blog.html
{% extends 'base.html' %}

{% block navbar %}
{% endblock navbar %}


{% block content %}{% endblock content %}

STRWEB/LR2/pizzeria/templates/blog/employee.html
{% extends 'base_blog.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/employee.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Сотрудники <img class="employee-icon" src="{% static 'pizza-svgrepo-com.svg' %}" alt="Icon"></h1>
        <div class="card-container">
            {% for employee in workers %}
                <div class="card">
                    <h2 class="card-title">{{ employee.name }}</h2>
                    <div style="display: flex">
                        <p class="card-description">{{ employee.description }}</p>
                        {% if employee.image %}
                            <img src="{{ employee.image.url }}" alt="{{ employee.name }}">
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

STRWEB/LR2/pizzeria/templates/blog/faq_list.html
{% extends 'base_blog.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/faq.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="faq-header">Словарь терминов и понятий <img class="faq-icon" src="{% static 'pizza-svgrepo-com.svg' %}" alt="Icon"></h1>

    {% for faq in faqs %}
    <section class="faq-section">
        <details class="faq-details">
            <summary class="faq-question">{{ faq.question }}</summary>
            <p class="faq-answer">{{ faq.answer }}<br>
                <em class="faq-added">Добавлено: {{ faq.added_date }}</em>
            </p>
        </details>
    </section>
    {% endfor %}
</div>
{% endblock %}

STRWEB/LR2/pizzeria/templates/blog/home.html
{% extends 'base_blog.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/homeblog.css' %}">
    <link rel="stylesheet" href="{% static 'css/preloader.css' %}">
    <link rel="stylesheet" href="{% static 'css/pizza.css' %}">
{% endblock %}
{% block content %}
    <div class="container" style="display: flex; flex-direction: row">
        <div class="loader">
            <div class="inner one"></div>
            <div class="inner two"></div>
        </div>
        <div style="margin-left: auto; background: rgba(232, 240, 248, 1); padding: 10px; width: 300px; height: auto;">
            <div class="pizza"></div>
        </div>
    </div>
    <div class="container ">
        <div class="news-section">
            <h1 class="news-title">Последние новости:<img class="news-icon" src="{% static 'pizza-svgrepo-com.svg' %}"
                                                          alt="Pizza Icon"></h1>
            {% if latest_post %}
                <h2 class="latest-post-title">{{ latest_post.title }}</h2>
                <p class="latest-post-content">{{ latest_post.content|truncatewords:50 }}</p>
                {# <a href="{% url 'blog:post_detail' latest_post.pk %}">Читать далее</a> #}
            {% else %}
                <h3 class="no-news">Новостей нет.</h3>
            {% endif %}
        </div>
        <div class="promo">
            <h3 class="promo-title">ПРОМО:</h3>
            <img class="promo-image" src="{% static random_image %}" alt="Random Image">
        </div>
        <div class="partners">
            <h4>Мы сотрудничаем:</h4>
            {% for logo in logo_companies %}
                <img class="partner-logo" src="{{ logo.image.url }}" alt="Company Logo">
            {% endfor %}
        </div>
    </div>
{% endblock %}

STRWEB/LR2/pizzeria/templates/blog/news_list.html
{% extends 'base_blog.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/news.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <h1 class="news-header">Новости <img class="news-icon" src="{% static 'pizza-svgrepo-com.svg' %}"
                                             alt="Pizza Icon"></h1>
        <div class="card-container">
            {% for post in posts %}
                <div class="card">
                    {% if post.image %}
                        <img src="{{ post.image.url }}" alt="{{ post.title }}">
                    {% endif %}
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-description">{{ post.content }}</p>
                    <a class="card-link" href="{% url 'blog:news_post' post.id %}">Читать далее</a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

STRWEB/LR2/pizzeria/templates/blog/news_post.html
{% extends 'base_blog.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/news.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h1>{{ post.title }}<img src="{% static 'pizza-svgrepo-com.svg' %}"></h1>

        {% if post.image %}
            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="post-image">
        {% endif %}
        <div class="article-content">
            {{ post.content|safe }}
        </div>
    </div>
{% endblock %}

STRWEB/LR2/pizzeria/templates/blog/promo_list.html
{% extends 'base_blog.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/promo.css' %}">
{% endblock %}

{% block content %}
<div class="promo-container">
    <h1 class="promo-header">Промокоды <img class="promo-icon" src="{% static 'pizza-svgrepo-com.svg' %}" alt="Icon"></h1>
    <ul class="promo-list">
        {% for promo in promos %}
            {% if promo.is_active %}
                <li class="promo-item active">
                    <div class="promo-card">
                        <h4 class="promo-code">Код {{ promo.code }} - скидка {{ promo.discount }}%</h4>
                    </div>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
    <h4 class="inactive-header">Неактивные промокоды:</h4>
    <ul class="promo-list">
        {% for promo in promos %}
            {% if not promo.is_active %}
                <li class="promo-item inactive">
                    <div class="promo-card">
                        <h4 class="promo-code">Код {{ promo.code }} - скидка {{ promo.discount }}%</h4>
                    </div>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</div>
{% endblock %}

STRWEB/LR2/pizzeria/templates/blog/reviews.html
{% extends 'base_blog.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/reviews.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Отзывы <img src="{% static 'pizza-svgrepo-com.svg' %}"></h1>
        {% if user.is_authenticated %}
            <h2>Оставить отзыв</h2>
            <form method="post" action="{% url 'blog:submit_review' %}">
                {% csrf_token %}
                <label for="title">Заголовок:</label><br>
                <input type="text" id="title" name="title" required><br>
                <label for="content">Содержание:</label><br>
                <textarea id="content" name="content" required></textarea><br>
                <button type="submit">Отправить</button>
            </form>
        {% else %}
            <p>Пожалуйста <a href="{% url 'registration:login' %}">залогиньтесь</a> чтобы оставить отзыв.</p>
        {% endif %}
{#    <div style=""#}
        <div class="container-review">
            <div class="card-list-container">
                {% for review in reviews %}
                    <div class="height-100 card">
                        <h4 class="card-title">{{ review.title }} от {{ review.user_name }}</h4>
                        <p class="card-description">{{ review.content|truncatewords:20 }}</p>
                        <time datetime="{{ review.added_date }}">{{ review.added_date }}</time>
                        {#        <a href="{% url 'blog:post_detail' post.pk %}">Читать далее</a>#}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

STRWEB/LR2/pizzeria/templates/blog/test.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/test.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <title>Styled Tables and Elements</title>
</head>
<body>
<header>
    <h1>Styled Tables and Elements</h1>
</header>

<main>
    <table class="styled-table">
        <caption>Example Table</caption>
        <thead>
        <tr>
            <th>Header 1</th>
            <th>Header 2</th>
            <th>Header 3</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Data 1</td>
            <td>Data 2</td>
            <td></td>
        </tr>
        <tr>
            <td>Data 3</td>
            <td>Data 4</td>
            <td>Data 5</td>
        </tr>
        <tr>
            <td>Data 3</td>
            <td>Data 4</td>
            <td>Data 5</td>
        </tr>
        <tr>
            <td>Data 3</td>
            <td>Data 4</td>
            <td>Data 5</td>
        </tr>
        <tr>
            <td>Data 3</td>
            <td>Data 4</td>
            <td>Data 5</td>
        </tr>
        </tbody>
    </table>

    <article>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <q lang="fr">Ceci est une citation</q>.</p>
    </article>

    <form>
        <input type="text" placeholder="Enter text" required>
        <input type="number" min="1" max="10" value="5">
        <input type="checkbox" checked>
        <button type="button">Submit</button>
    </form>

    <ul class="styled-list">
        <li>Item 1</li>
        <li>Item 2</li>
        <li>Item 3</li>
    </ul>
</main>
</body>
</html>

STRWEB/LR2/pizzeria/templates/blog/vacancy.html
{% extends 'base_blog.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/vacancy.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1>Вакансии  <img src="{% static 'pizza-svgrepo-com.svg' %}" alt="Pizza Icon"></h1>
    <ul class="vacancy-list">
        {% for vacancy in vacancies %}
            <li class="vacancy-item">
                <p class="vacancy-description">{{ vacancy.description }}</p>
                <hr class="vacancy-divider">
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}